sudo: false
language: node_js
cache: yarn

node_js:
  - 8
  - 6
  - 4

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  - yarn clean
  - yarn build

script:
  - yarn test

stages:
  - lint
  - test
  - name: publish
    if: branch = master
      AND repo = boopathi/travis-node-build-stages-test
      AND type = push

jobs:
  include:
    - stage: lint
      node_js: 8
      script: yarn lint
    - stage: publish
      node_js: 8
      deploy:
        provider: script
        script: yarn publish-master
