sudo: false
langauage: node_js
cache: yarn

node_js:
  - 8
  - 6
  - 4

before_script:
  - yarn clean
  - yarn build

script:
  - yarn test

stages:
  - lint
  - test
  - name: publish
    if: branch = master
    if: repo = boopathi/travis-node-build-stages-test
    if: type = push
    if: NOT (env(TRAVIS_COMMIT_MESSAGE) =~ \[skip publish\])

jobs:
  include:
    - stage: lint
      node_js: 8
      script: yarn lint
    - stage: publish
      node_js: 8
      script: yarn publish-master
